mybatis:
    config-location: classpath:mybatis-config.xml
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.model
redis:
    host: 192.168.3.6
    poolMaxIdle: 500
    poolMaxTotal: 1000
    poolMaxWait: 500
    port: 6379
    timeout: 10
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 100
        maxActive: 1000
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 500
        password: Admin@123
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.3.6:3306/cto?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        username: root
        validationQuery: select 'x'
    freemarker:
        cache: true
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path: classpath:/web
    profiles:
        active: dev
    rabbitmq:
        host: 193.112.73.82
        listener:
            simple:
                auto-startup: true
                concurrency: 10
                default-requeue-rejected: true
                max-concurrency: 10
                prefetch: 1
        password: guest
        port: 5672
        template:
            retry:
                enabled: 'true'
                initial-interval: 1000
                max-attempts: 3
                max-interval: 10000
                multiplier: 1.0
        username: guest
        virtual-host: /
logging:
    level:
      com.mapper : info
